%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#fff2cc'}}}%%
flowchart TD
A[<img src='https://cdn-icons-png.flaticon.com/512/1086/1086741.png' width='25'/> Sensores Físicos] --> B[<img src='https://cdn-icons-png.flaticon.com/512/3601/3601624.png' width='25'/> Prometheus]
B --> C[<img src='https://cdn-icons-png.flaticon.com/512/2620/2620971.png' width='25'/> Grafana]
C --> D[<img src='https://cdn-icons-png.flaticon.com/512/2103/2103633.png' width='25'/> Dashboard 3D]

style A fill:#f9cb9c,stroke:#e69138
style B fill:#b6d7a8,stroke:#6aa84f
style C fill:#a2c4c9,stroke:#3d85c6
style D fill:#d5a6bd,stroke:#a64d79
