name: Revive MechBot

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t mechbot .
      - run: docker run --rm mechbot python -m pytest tests/
